unown: {learnset: {
		aurasphere: ["7M"],
		calmmind: ["7M"],
		dazzlinggleam: ["7M"],
		dracometeor: ["7M"],
		dragonpulse: ["7M"],
		earthpower: ["7M"],
		energyball: ["7M"],
		fireblast: ["7M"],
		flamethrower:["7M"],
		flashcannon: ["7M"],
		gigadrain: ["7M"],
		focusblast: ["7M"],
		hiddenpower: ["7M", "7L1", "7V", "6L1", "5L1", "4L1", "7L1"],
		moonblast: ["7M"],
		protect: ["7M"],
		psychic: ["7M"],
		psyshock: ["7M"],
		psystrike: ["7M"],
		recover: ["7M"],
		shadowball: ["7M"],
		thunderbolt: ["7M"],
		voltswitch: ["7M"],
	}},